import 'app_language.dart';

/// Core AgriN UI translations. Unknown strings intentionally fall back to English.
String tr(String key, [AppLanguage? language]) {
  final code = (language ?? supportedLanguages.first).code;
  return _translations[code]?[key] ?? _translations['en']?[key] ?? key;
}

const _translations = <String, Map<String, String>>{
  'en': {
    'FARM':'FARM','DOCTOR':'DOCTOR','HISTORY':'HISTORY','NETWORK':'NETWORK','INDIA':'INDIA',
    'AGRICULTURAL INTELLIGENCE':'AGRICULTURAL INTELLIGENCE',
    'Evidence from weather, soil, satellite and history — brought together for better farm decisions.':'Evidence from weather, soil, satellite and history — brought together for better farm decisions.',
    'ANALYZE FARM':'ANALYZE FARM','CROP DOCTOR':'CROP DOCTOR','THE FARM / 01':'THE FARM / 01',
    'AgriN treats every observation as evidence — with its source, date and limitations kept visible.':'AgriN treats every observation as evidence — with its source, date and limitations kept visible.',
    'WEATHER':'WEATHER','SOIL':'SOIL','SATELLITE':'SATELLITE','AI':'AI','FARM INTELLIGENCE':'FARM INTELLIGENCE',
    'AI AGRO-ADVISORY':'AI AGRO-ADVISORY','REGENERATIVE FARMING':'REGENERATIVE FARMING','HISTORICAL INTELLIGENCE':'HISTORICAL INTELLIGENCE',
    'INTELLIGENCE / 02':'INTELLIGENCE / 02','INTELLIGENCE AGENT':'INTELLIGENCE AGENT','FROM SIGNALS\nTO DECISIONS.':'FROM SIGNALS\nTO DECISIONS.',
    'RUN INTELLIGENCE AGENT':'RUN INTELLIGENCE AGENT','NETWORK / 07':'NETWORK / 07','OPEN AGRICULTURAL\nOBSERVATIONS.':'OPEN AGRICULTURAL\nOBSERVATIONS.','OPEN NETWORK':'OPEN NETWORK',
    'EVIDENCE • RESILIENCE • OPEN DATA':'EVIDENCE • RESILIENCE • OPEN DATA','LIVING\nLAND':'LIVING\nLAND','FIELD':'FIELD',
  },
  'hi': {
    'FARM':'खेत','DOCTOR':'डॉक्टर','HISTORY':'इतिहास','NETWORK':'नेटवर्क','INDIA':'भारत','AGRICULTURAL INTELLIGENCE':'कृषि बुद्धिमत्ता',
    'Evidence from weather, soil, satellite and history — brought together for better farm decisions.':'मौसम, मिट्टी, उपग्रह और इतिहास के प्रमाणों को बेहतर खेती के निर्णयों के लिए एक साथ लाया गया है।',
    'ANALYZE FARM':'खेत का विश्लेषण','CROP DOCTOR':'फसल डॉक्टर','THE FARM / 01':'खेत / 01','AgriN treats every observation as evidence — with its source, date and limitations kept visible.':'AgriN हर अवलोकन को प्रमाण मानता है — स्रोत, तारीख और सीमाएँ स्पष्ट रहती हैं।',
    'WEATHER':'मौसम','SOIL':'मिट्टी','SATELLITE':'उपग्रह','AI':'एआई','FARM INTELLIGENCE':'खेत बुद्धिमत्ता','AI AGRO-ADVISORY':'एआई कृषि सलाह','REGENERATIVE FARMING':'पुनर्योजी खेती','HISTORICAL INTELLIGENCE':'ऐतिहासिक बुद्धिमत्ता',
    'INTELLIGENCE / 02':'बुद्धिमत्ता / 02','INTELLIGENCE AGENT':'बुद्धिमत्ता एजेंट','FROM SIGNALS\nTO DECISIONS.':'संकेतों से\nनिर्णयों तक','RUN INTELLIGENCE AGENT':'बुद्धिमत्ता एजेंट चलाएँ',
    'NETWORK / 07':'नेटवर्क / 07','OPEN AGRICULTURAL\nOBSERVATIONS.':'खुले कृषि\nअवलोकन','OPEN NETWORK':'नेटवर्क खोलें','EVIDENCE • RESILIENCE • OPEN DATA':'प्रमाण • लचीलापन • खुला डेटा','LIVING\nLAND':'जीवंत\nभूमि','FIELD':'खेत'
  },
  'mr': {
    'FARM':'शेत','DOCTOR':'डॉक्टर','HISTORY':'इतिहास','NETWORK':'नेटवर्क','INDIA':'भारत','AGRICULTURAL INTELLIGENCE':'कृषी बुद्धिमत्ता',
    'Evidence from weather, soil, satellite and history — brought together for better farm decisions.':'हवामान, माती, उपग्रह आणि इतिहासातील पुरावे चांगल्या शेती निर्णयांसाठी एकत्र केले आहेत.',
    'ANALYZE FARM':'शेताचे विश्लेषण','CROP DOCTOR':'पीक डॉक्टर','THE FARM / 01':'शेत / 01','AgriN treats every observation as evidence — with its source, date and limitations kept visible.':'AgriN प्रत्येक निरीक्षणाला पुरावा मानते — स्रोत, तारीख आणि मर्यादा स्पष्ट ठेवते.',
    'WEATHER':'हवामान','SOIL':'माती','SATELLITE':'उपग्रह','AI':'एआय','FARM INTELLIGENCE':'शेती बुद्धिमत्ता','AI AGRO-ADVISORY':'एआय कृषी सल्ला','REGENERATIVE FARMING':'पुनरुत्पादक शेती','HISTORICAL INTELLIGENCE':'ऐतिहासिक बुद्धिमत्ता',
    'INTELLIGENCE / 02':'बुद्धिमत्ता / 02','INTELLIGENCE AGENT':'बुद्धिमत्ता एजंट','FROM SIGNALS\nTO DECISIONS.':'संकेतांपासून\nनिर्णयांपर्यंत','RUN INTELLIGENCE AGENT':'बुद्धिमत्ता एजंट चालवा','NETWORK / 07':'नेटवर्क / 07','OPEN AGRICULTURAL\nOBSERVATIONS.':'खुले कृषी\nनिरीक्षण','OPEN NETWORK':'नेटवर्क उघडा','EVIDENCE • RESILIENCE • OPEN DATA':'पुरावे • लवचिकता • खुला डेटा','LIVING\nLAND':'जिवंत\nजमीन','FIELD':'शेत'
  },
  'bn': {'FARM':'খামার','DOCTOR':'ডাক্তার','HISTORY':'ইতিহাস','NETWORK':'নেটওয়ার্ক','INDIA':'ভারত','AGRICULTURAL INTELLIGENCE':'কৃষি বুদ্ধিমত্তা','ANALYZE FARM':'খামার বিশ্লেষণ','CROP DOCTOR':'ফসল ডাক্তার','WEATHER':'আবহাওয়া','SOIL':'মাটি','SATELLITE':'স্যাটেলাইট','AI':'এআই','FARM INTELLIGENCE':'খামার বুদ্ধিমত্তা','AI AGRO-ADVISORY':'এআই কৃষি পরামর্শ','REGENERATIVE FARMING':'পুনরুজ্জীবনশীল কৃষি','HISTORICAL INTELLIGENCE':'ঐতিহাসিক বুদ্ধিমত্তা','INTELLIGENCE AGENT':'বুদ্ধিমত্তা এজেন্ট','RUN INTELLIGENCE AGENT':'বুদ্ধিমত্তা এজেন্ট চালান','OPEN NETWORK':'নেটওয়ার্ক খুলুন','FIELD':'ক্ষেত'},
  'te': {'FARM':'పొలం','DOCTOR':'డాక్టర్','HISTORY':'చరిత్ర','NETWORK':'నెట్‌వర్క్','INDIA':'భారత్','AGRICULTURAL INTELLIGENCE':'వ్యవసాయ మేధస్సు','ANALYZE FARM':'పొలాన్ని విశ్లేషించండి','CROP DOCTOR':'పంట డాక్టర్','WEATHER':'వాతావరణం','SOIL':'నేల','SATELLITE':'ఉపగ్రహం','AI':'ఏఐ','FARM INTELLIGENCE':'వ్యవసాయ మేధస్సు','AI AGRO-ADVISORY':'ఏఐ వ్యవసాయ సలహా','REGENERATIVE FARMING':'పునరుత్పత్తి వ్యవసాయం','HISTORICAL INTELLIGENCE':'చారిత్రక మేధస్సు','INTELLIGENCE AGENT':'మేధస్సు ఏజెంట్','RUN INTELLIGENCE AGENT':'మేధస్సు ఏజెంట్ నడపండి','OPEN NETWORK':'నెట్‌వర్క్ తెరవండి','FIELD':'పొలం'},
  'ta': {'FARM':'பண்ணை','DOCTOR':'மருத்துவர்','HISTORY':'வரலாறு','NETWORK':'வலையமைப்பு','INDIA':'இந்தியா','AGRICULTURAL INTELLIGENCE':'விவசாய நுண்ணறிவு','ANALYZE FARM':'பண்ணையை பகுப்பாய்வு செய்','CROP DOCTOR':'பயிர் மருத்துவர்','WEATHER':'வானிலை','SOIL':'மண்','SATELLITE':'செயற்கைக்கோள்','AI':'AI','FARM INTELLIGENCE':'பண்ணை நுண்ணறிவு','AI AGRO-ADVISORY':'AI வேளாண் ஆலோசனை','REGENERATIVE FARMING':'மறுஉற்பத்தி விவசாயம்','HISTORICAL INTELLIGENCE':'வரலாற்று நுண்ணறிவு','INTELLIGENCE AGENT':'நுண்ணறிவு முகவர்','RUN INTELLIGENCE AGENT':'நுண்ணறிவு முகவரை இயக்கு','OPEN NETWORK':'வலையமைப்பைத் திற','FIELD':'வயல்'},
  'gu': {'FARM':'ખેતર','DOCTOR':'ડોક્ટર','HISTORY':'ઇતિહાસ','NETWORK':'નેટવર્ક','INDIA':'ભારત','AGRICULTURAL INTELLIGENCE':'કૃષિ બુદ્ધિમત્તા','ANALYZE FARM':'ખેતરનું વિશ્લેષણ','CROP DOCTOR':'પાક ડોક્ટર','WEATHER':'હવામાન','SOIL':'માટી','SATELLITE':'ઉપગ્રહ','AI':'એઆઈ','FARM INTELLIGENCE':'ખેતર બુદ્ધિમત્તા','AI AGRO-ADVISORY':'એઆઈ કૃષિ સલાહ','REGENERATIVE FARMING':'પુનર્જીવિત ખેતી','HISTORICAL INTELLIGENCE':'ઐતિહાસિક બુદ્ધિમત્તા','INTELLIGENCE AGENT':'બુદ્ધિમત્તા એજન્ટ','RUN INTELLIGENCE AGENT':'બુદ્ધિમત્તા એજન્ટ ચલાવો','OPEN NETWORK':'નેટવર્ક ખોલો','FIELD':'ખેતર'},
  'kn': {'FARM':'ಹೊಲ','DOCTOR':'ವೈದ್ಯ','HISTORY':'ಇತಿಹಾಸ','NETWORK':'ನೆಟ್‌ವರ್ಕ್','INDIA':'ಭಾರತ','AGRICULTURAL INTELLIGENCE':'ಕೃಷಿ ಬುದ್ಧಿಮತ್ತೆ','ANALYZE FARM':'ಹೊಲ ವಿಶ್ಲೇಷಿಸಿ','CROP DOCTOR':'ಬೆಳೆ ವೈದ್ಯ','WEATHER':'ಹವಾಮಾನ','SOIL':'ಮಣ್ಣು','SATELLITE':'ಉಪಗ್ರಹ','AI':'ಎಐ','FARM INTELLIGENCE':'ಹೊಲ ಬುದ್ಧಿಮತ್ತೆ','AI AGRO-ADVISORY':'ಎಐ ಕೃಷಿ ಸಲಹೆ','REGENERATIVE FARMING':'ಪುನರುತ್ಪಾದಕ ಕೃಷಿ','HISTORICAL INTELLIGENCE':'ಐತಿಹಾಸಿಕ ಬುದ್ಧಿಮತ್ತೆ','INTELLIGENCE AGENT':'ಬುದ್ಧಿಮತ್ತೆ ಏಜೆಂಟ್','RUN INTELLIGENCE AGENT':'ಬುದ್ಧಿಮತ್ತೆ ಏಜೆಂಟ್ ಚಾಲನೆ','OPEN NETWORK':'ನೆಟ್‌ವರ್ಕ್ ತೆರೆಯಿರಿ','FIELD':'ಹೊಲ'},
  'ml': {'FARM':'കൃഷിയിടം','DOCTOR':'ഡോക്ടർ','HISTORY':'ചരിത്രം','NETWORK':'നെറ്റ്‌വർക്ക്','INDIA':'ഇന്ത്യ','AGRICULTURAL INTELLIGENCE':'കാർഷിക ബുദ്ധി','ANALYZE FARM':'കൃഷിയിടം വിശകലനം ചെയ്യുക','CROP DOCTOR':'വിള ഡോക്ടർ','WEATHER':'കാലാവസ്ഥ','SOIL':'മണ്ണ്','SATELLITE':'ഉപഗ്രഹം','AI':'എഐ','FARM INTELLIGENCE':'കാർഷിക ബുദ്ധി','AI AGRO-ADVISORY':'എഐ കാർഷിക ഉപദേശം','REGENERATIVE FARMING':'പുനരുജ്ജീവന കൃഷി','HISTORICAL INTELLIGENCE':'ചരിത്ര ബുദ്ധി','INTELLIGENCE AGENT':'ബുദ്ധി ഏജന്റ്','RUN INTELLIGENCE AGENT':'ബുദ്ധി ഏജന്റ് പ്രവർത്തിപ്പിക്കുക','OPEN NETWORK':'നെറ്റ്‌വർക്ക് തുറക്കുക','FIELD':'കൃഷിയിടം'},
  'pa': {'FARM':'ਖੇਤ','DOCTOR':'ਡਾਕਟਰ','HISTORY':'ਇਤਿਹਾਸ','NETWORK':'ਨੈੱਟਵਰਕ','INDIA':'ਭਾਰਤ','AGRICULTURAL INTELLIGENCE':'ਖੇਤੀਬਾੜੀ ਬੁੱਧੀ','ANALYZE FARM':'ਖੇਤ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ','CROP DOCTOR':'ਫਸਲ ਡਾਕਟਰ','WEATHER':'ਮੌਸਮ','SOIL':'ਮਿੱਟੀ','SATELLITE':'ਸੈਟੇਲਾਈਟ','AI':'ਏਆਈ','FARM INTELLIGENCE':'ਖੇਤ ਬੁੱਧੀ','AI AGRO-ADVISORY':'ਏਆਈ ਖੇਤੀ ਸਲਾਹ','REGENERATIVE FARMING':'ਪੁਨਰਜੀਵਿਤ ਖੇਤੀ','HISTORICAL INTELLIGENCE':'ਇਤਿਹਾਸਕ ਬੁੱਧੀ','INTELLIGENCE AGENT':'ਬੁੱਧੀ ਏਜੰਟ','RUN INTELLIGENCE AGENT':'ਬੁੱਧੀ ਏਜੰਟ ਚਲਾਓ','OPEN NETWORK':'ਨੈੱਟਵਰਕ ਖੋਲ੍ਹੋ','FIELD':'ਖੇਤ'},
  'as': {'FARM':'খেতি','DOCTOR':'ডাক্তৰ','HISTORY':'ইতিহাস','NETWORK':'নেটৱৰ্ক','INDIA':'ভাৰত','AGRICULTURAL INTELLIGENCE':'কৃষি বুদ্ধিমত্তা','ANALYZE FARM':'খেতি বিশ্লেষণ','CROP DOCTOR':'শস্য চিকিৎসক','WEATHER':'বতৰ','SOIL':'মাটি','SATELLITE':'উপগ্ৰহ','AI':'এআই','FARM INTELLIGENCE':'কৃষি বুদ্ধিমত্তা','AI AGRO-ADVISORY':'এআই কৃষি পৰামৰ্শ','REGENERATIVE FARMING':'পুনৰুজ্জীৱিত কৃষি','HISTORICAL INTELLIGENCE':'ঐতিহাসিক বুদ্ধিমত্তা','INTELLIGENCE AGENT':'বুদ্ধিমত্তা এজেণ্ট','RUN INTELLIGENCE AGENT':'বুদ্ধিমত্তা এজেণ্ট চলাওক','OPEN NETWORK':'নেটৱৰ্ক খোলক','FIELD':'খেতি'},
  'or': {'FARM':'କ୍ଷେତ','DOCTOR':'ଡାକ୍ତର','HISTORY':'ଇତିହାସ','NETWORK':'ନେଟୱର୍କ','INDIA':'ଭାରତ','AGRICULTURAL INTELLIGENCE':'କୃଷି ବୁଦ୍ଧିମତ୍ତା','ANALYZE FARM':'କ୍ଷେତ ବିଶ୍ଳେଷଣ','CROP DOCTOR':'ଫସଲ ଡାକ୍ତର','WEATHER':'ପାଣିପାଗ','SOIL':'ମାଟି','SATELLITE':'ଉପଗ୍ରହ','AI':'ଏଆଇ','FARM INTELLIGENCE':'କୃଷି ବୁଦ୍ଧିମତ୍ତା','AI AGRO-ADVISORY':'ଏଆଇ କୃଷି ପରାମର୍ଶ','REGENERATIVE FARMING':'ପୁନର୍ଜୀବନ କୃଷି','HISTORICAL INTELLIGENCE':'ଐତିହାସିକ ବୁଦ୍ଧିମତ୍ତା','INTELLIGENCE AGENT':'ବୁଦ୍ଧିମତ୍ତା ଏଜେଣ୍ଟ','RUN INTELLIGENCE AGENT':'ବୁଦ୍ଧିମତ୍ତା ଏଜେଣ୍ଟ ଚଲାନ୍ତୁ','OPEN NETWORK':'ନେଟୱର୍କ ଖୋଲନ୍ତୁ','FIELD':'କ୍ଷେତ'},
  'ur': {'FARM':'کھیت','DOCTOR':'ڈاکٹر','HISTORY':'تاریخ','NETWORK':'نیٹ ورک','INDIA':'بھارت','AGRICULTURAL INTELLIGENCE':'زرعی ذہانت','ANALYZE FARM':'کھیت کا تجزیہ','CROP DOCTOR':'فصل ڈاکٹر','WEATHER':'موسم','SOIL':'مٹی','SATELLITE':'سیٹلائٹ','AI':'اے آئی','FARM INTELLIGENCE':'زرعی ذہانت','AI AGRO-ADVISORY':'اے آئی زرعی مشورہ','REGENERATIVE FARMING':'تجدیدی زراعت','HISTORICAL INTELLIGENCE':'تاریخی ذہانت','INTELLIGENCE AGENT':'ذہانت ایجنٹ','RUN INTELLIGENCE AGENT':'ذہانت ایجنٹ چلائیں','OPEN NETWORK':'نیٹ ورک کھولیں','FIELD':'کھیت'},
  'sa': {'FARM':'क्षेत्रम्','DOCTOR':'वैद्यः','HISTORY':'इतिहासः','NETWORK':'जालम्','INDIA':'भारतः','AGRICULTURAL INTELLIGENCE':'कृषिबुद्धिमत्ता','ANALYZE FARM':'क्षेत्रं विश्लेषय','CROP DOCTOR':'सस्यवैद्यः','WEATHER':'वायुमण्डलम्','SOIL':'मृत्तिका','SATELLITE':'उपग्रहः','AI':'कृत्रिमबुद्धिः','FARM INTELLIGENCE':'कृषिबुद्धिमत्ता','AI AGRO-ADVISORY':'कृषिपरामर्शः','REGENERATIVE FARMING':'पुनरुत्पादककृषिः','HISTORICAL INTELLIGENCE':'ऐतिहासिकबुद्धिमत्ता','INTELLIGENCE AGENT':'बुद्धिमत्तादूतः','RUN INTELLIGENCE AGENT':'बुद्धिमत्तादूतं चालय','OPEN NETWORK':'जालं उद्घाटय','FIELD':'क्षेत्रम्'},
  'mai': {'FARM':'खेत','DOCTOR':'डॉक्टर','HISTORY':'इतिहास','NETWORK':'नेटवर्क','INDIA':'भारत','AGRICULTURAL INTELLIGENCE':'कृषि बुद्धिमत्ता','ANALYZE FARM':'खेतक विश्लेषण','CROP DOCTOR':'फसल डॉक्टर','WEATHER':'मौसम','SOIL':'माटि','SATELLITE':'उपग्रह','AI':'एआई','FARM INTELLIGENCE':'खेत बुद्धिमत्ता','AI AGRO-ADVISORY':'एआई कृषि सलाह','REGENERATIVE FARMING':'पुनर्योजी खेती','HISTORICAL INTELLIGENCE':'ऐतिहासिक बुद्धिमत्ता','INTELLIGENCE AGENT':'बुद्धिमत्ता एजेंट','RUN INTELLIGENCE AGENT':'बुद्धिमत्ता एजेंट चलाउ','OPEN NETWORK':'नेटवर्क खोलू','FIELD':'खेत'},
  'ne': {'FARM':'खेत','DOCTOR':'डाक्टर','HISTORY':'इतिहास','NETWORK':'सञ्जाल','INDIA':'भारत','AGRICULTURAL INTELLIGENCE':'कृषि बुद्धिमत्ता','ANALYZE FARM':'खेत विश्लेषण','CROP DOCTOR':'बाली डाक्टर','WEATHER':'मौसम','SOIL':'माटो','SATELLITE':'उपग्रह','AI':'एआई','FARM INTELLIGENCE':'खेत बुद्धिमत्ता','AI AGRO-ADVISORY':'एआई कृषि सल्लाह','REGENERATIVE FARMING':'पुनरुत्पादक कृषि','HISTORICAL INTELLIGENCE':'ऐतिहासिक बुद्धिमत्ता','INTELLIGENCE AGENT':'बुद्धिमत्ता एजेन्ट','RUN INTELLIGENCE AGENT':'बुद्धिमत्ता एजेन्ट चलाउनुहोस्','OPEN NETWORK':'सञ्जाल खोल्नुहोस्','FIELD':'खेत'},
  'kok': {'FARM':'शेत','DOCTOR':'डॉक्टर','HISTORY':'इतिहास','NETWORK':'नेटवर्क','INDIA':'भारत','AGRICULTURAL INTELLIGENCE':'शेती बुद्धिमत्ता','ANALYZE FARM':'शेत विश्लेषण','CROP DOCTOR':'पीक डॉक्टर','WEATHER':'हवामान','SOIL':'माती','SATELLITE':'उपग्रह','AI':'एआय','FARM INTELLIGENCE':'शेती बुद्धिमत्ता','AI AGRO-ADVISORY':'एआय कृषी सल्लो','REGENERATIVE FARMING':'पुनरुत्पादक शेती','HISTORICAL INTELLIGENCE':'इतिहास बुद्धिमत्ता','INTELLIGENCE AGENT':'बुद्धिमत्ता एजंट','RUN INTELLIGENCE AGENT':'बुद्धिमत्ता एजंट चालोवप','OPEN NETWORK':'नेटवर्क उगडात','FIELD':'शेत'},
  'doi': {'FARM':'खेत','DOCTOR':'डाक्टर','HISTORY':'इतिहास','NETWORK':'नेटवर्क','INDIA':'भारत','AGRICULTURAL INTELLIGENCE':'कृषि बुद्धिमत्ता','ANALYZE FARM':'खेतक विश्लेषण','CROP DOCTOR':'फसल डाक्टर','WEATHER':'मौसम','SOIL':'माटि','SATELLITE':'उपग्रह','AI':'एआई','FARM INTELLIGENCE':'खेत बुद्धिमत्ता','AI AGRO-ADVISORY':'एआई कृषि सलाह','REGENERATIVE FARMING':'पुनर्योजी खेती','HISTORICAL INTELLIGENCE':'ऐतिहासिक बुद्धिमत्ता','INTELLIGENCE AGENT':'बुद्धिमत्ता एजेंट','RUN INTELLIGENCE AGENT':'बुद्धिमत्ता एजेंट चलाउ','OPEN NETWORK':'नेटवर्क खोलू','FIELD':'खेत'},
  'ks': {'FARM':'کھیت','DOCTOR':'ڈاکٹر','HISTORY':'تاریخ','NETWORK':'نیٹ ورک','INDIA':'ہند','AGRICULTURAL INTELLIGENCE':'زرعی ذہانت','ANALYZE FARM':'کھیت تجزیہ','CROP DOCTOR':'فصل ڈاکٹر','WEATHER':'موسم','SOIL':'مٹی','SATELLITE':'سیٹلائٹ','AI':'اے آئی','FARM INTELLIGENCE':'کھیت ذہانت','AI AGRO-ADVISORY':'اے آئی زرعی مشورہ','REGENERATIVE FARMING':'تجدیدی زراعت','HISTORICAL INTELLIGENCE':'تاریخی ذہانت','INTELLIGENCE AGENT':'ذہانت ایجنٹ','RUN INTELLIGENCE AGENT':'ذہانت ایجنٹ چلاؤ','OPEN NETWORK':'نیٹ ورک کھولو','FIELD':'کھیت'},
  'mni': {'FARM':'ꯐꯥꯔꯝ','DOCTOR':'ꯗꯣꯛꯇꯔ','HISTORY':'ꯑꯇꯣꯞꯄ','NETWORK':'ꯅꯦꯠꯋꯔꯛ','INDIA':'ꯏꯟꯗꯤꯌꯥ','AGRICULTURAL INTELLIGENCE':'ꯂꯩꯉꯥꯛ ꯃꯤꯔꯣꯜ','ANALYZE FARM':'ꯐꯥꯔꯝ ꯁꯦꯝꯗꯣꯛ','CROP DOCTOR':'ꯀ꯭ꯔꯣꯞ ꯗꯣꯛꯇꯔ','WEATHER':'ꯋꯦꯗꯔ','SOIL':'ꯂꯩꯉꯥꯛ','SATELLITE':'ꯁꯦꯇꯦꯂꯥꯏꯠ','AI':'AI','FIELD':'ꯐꯥꯔꯝ'},
  'brx': {'FARM':'फार्म','DOCTOR':'डाक्टर','HISTORY':'इतिहास','NETWORK':'नेटवर्क','INDIA':'भारत','AGRICULTURAL INTELLIGENCE':'फसल बिद्याज्ञान','ANALYZE FARM':'फार्म विश्लेषण','CROP DOCTOR':'फसल डाक्टर','WEATHER':'हावामान','SOIL':'माटि','SATELLITE':'सैटेलाइट','AI':'एआई','FIELD':'फार्म'},
  'sat': {'FARM':'ᱡᱚᱢᱤ','DOCTOR':'ᱫᱟᱠᱛᱟᱨ','HISTORY':'ᱤᱛᱤᱦᱟᱥ','NETWORK':'ᱱᱮᱴᱣᱟᱹᱨᱠ','INDIA':'ᱵᱷᱟᱨᱚᱛ','AGRICULTURAL INTELLIGENCE':'ᱡᱚᱢᱤ ᱵᱩᱫᱷᱤ','ANALYZE FARM':'ᱡᱚᱢᱤ ᱵᱤᱥᱞᱮᱥᱚᱱ','CROP DOCTOR':'ᱯᱷᱚᱥᱚᱞ ᱫᱟᱠᱛᱟᱨ','WEATHER':'ᱦᱟᱣᱟᱢᱟᱱ','SOIL':'ᱡᱚᱢᱤ','SATELLITE':'ᱥᱟᱴᱮᱞᱟᱭᱤᱴ','AI':'AI','FIELD':'ᱡᱚᱢᱤ'},
  'sd': {'FARM':'کيت','DOCTOR':'ڊاڪٽر','HISTORY':'تاريخ','NETWORK':'نيٽورڪ','INDIA':'ڀارت','AGRICULTURAL INTELLIGENCE':'زرعي ذهانت','ANALYZE FARM':'کيت جو تجزيو','CROP DOCTOR':'فصل ڊاڪٽر','WEATHER':'موسم','SOIL':'مٽي','SATELLITE':'سيٽلائيٽ','AI':'اي آءِ','FIELD':'کيت'},
};